version: '3.8'
services:
  dev-emp:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: employeedb

# Cara menjalankan
# docker compose up dev-emp -d